version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /app/src
        volumes:
            - ./src:/app/src
        ports:
            - "8989:8080"
        networks:
            - laravel
    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'db'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ./docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
